# Osaka Dark Colors for Hyprlock
$bg0    = rgb(001a1f)
$bg1    = rgb(001215)
$bg2    = rgb(002b36)
$bg3    = rgb(003842)
$bg4    = rgb(07404a)

$red    = rgb(de322e)
$orange = rgb(c94c16)
$yellow = rgb(b28700)
$green  = rgb(869900)
$aqua   = rgb(2a9f97)
$blue   = rgb(278bd2)
$purple = rgb(d53683)

$fg     = rgb(839395)

$grey0  = rgb(587175)
$grey1  = rgb(657b83)
$grey2  = rgb(839395)

$fgAlpha     = 839395
$purpleAlpha = d53683
