# Horizon Colors for Kitty
background #1C1E26
foreground #D5D8DA
cursor     #D5D8DA
selection_background #44465B
selection_foreground #D5D8DA

color0  #2E303E
color8  #6C6F93
color1  #E95678
color9  #E95678
color2  #29D398
color10 #29D398
color3  #FAC29A
color11 #FAC29A
color4  #26BBD9
color12 #26BBD9
color5  #EE64AC
color13 #EE64AC
color6  #59E1E3
color14 #59E1E3
color7  #D5D8DA
color15 #FDF0ED
