[colors-dark]
foreground=D5D8DA
background=1C1E26
selection-background=44465B

## Normal/regular colors (color palette 0-7)
regular0=2E303E  # black
regular1=E95678  # red
regular2=29D398  # green
regular3=FAC29A  # yellow
regular4=26BBD9  # blue
regular5=EE64AC  # magenta
regular6=59E1E3  # cyan
regular7=D5D8DA  # white

## Bright colors (color palette 8-15)
bright0=6C6F93   # bright black
bright1=F09383   # bright red (orange)
bright2=29D398   # bright green
bright3=FAC29A   # bright yellow
bright4=26BBD9   # bright blue
bright5=EE64AC   # bright magenta
bright6=59E1E3   # bright cyan
bright7=FDF0ED   # bright white

## Dimmed colors
dim0=F09383      # orange
dim1=44465B      # bg_highlight (Selection bg)
