# Official Tokyo Night Colors for Hyprlock
$bg0    = rgb(1a1b26)
$bg1    = rgb(16161e)
$bg2    = rgb(1f2335)
$bg3    = rgb(24283b)
$bg4    = rgb(292e42)

$red    = rgb(f7768e)
$orange = rgb(ff9e64)
$yellow = rgb(e0af68)
$green  = rgb(9ece6a)
$aqua   = rgb(7dcfff)
$blue   = rgb(7aa2f7)
$purple = rgb(bb9af7)

$fg     = rgb(c0caf5)

$grey0  = rgb(3b4261)
$grey1  = rgb(414868)
$grey2  = rgb(565f89)

$fgAlpha     = c0caf5
$purpleAlpha = bb9af7
