[colors-dark]
foreground=FBD5AE
background=012423
selection-background=324440

## Normal/regular colors (color palette 0-7)
regular0=1C3A38  # black
regular1=D4493F  # red
regular2=90B640  # green
regular3=E5B73E  # yellow
regular4=3C7B80  # blue
regular5=694E68  # magenta
regular6=5EA89A  # cyan
regular7=FBD5AE  # white

## Bright colors (color palette 8-15)
bright0=324440   # bright black
bright1=DB9D6F   # bright red (orange)
bright2=90B640   # bright green
bright3=E5B73E   # bright yellow
bright4=3C7B80   # bright blue
bright5=694E68   # bright magenta
bright6=5EA89A   # bright cyan
bright7=E9C8A1   # bright white

## Dimmed colors
dim0=DB9D6F      # orange
dim1=324440      # bg_highlight (Selection bg)
