# Horizon Colors for Hyprlock
$bg0    = rgb(1C1E26)
$bg1    = rgb(232530)
$bg2    = rgb(2E303E)
$bg3    = rgb(44465B)
$bg4    = rgb(1A1C23)

$red    = rgb(E95678)
$orange = rgb(F09383)
$yellow = rgb(FAC29A)
$green  = rgb(29D398)
$aqua   = rgb(59E1E3)
$blue   = rgb(26BBD9)
$purple = rgb(EE64AC)

$fg     = rgb(D5D8DA)

$grey0  = rgb(6C6F93)
$grey1  = rgb(44465B)
$grey2  = rgb(2E303E)

$fgAlpha     = D5D8DA
$purpleAlpha = EE64AC
