# Rxyhn Earthy Pine for Hyprlock
$bg0    = rgb(012423)
$bg1    = rgb(023432)
$bg2    = rgb(1C3A38)
$bg3    = rgb(122A28)
$bg4    = rgb(1A2F2B)

$red    = rgb(D4493F)
$orange = rgb(DB9D6F)
$yellow = rgb(E5B73E)
$green  = rgb(90B640)
$aqua   = rgb(5EA89A)
$blue   = rgb(3C7B80)
$purple = rgb(694E68)

$fg     = rgb(FBD5AE)

$grey0  = rgb(324440)
$grey1  = rgb(435C56)
$grey2  = rgb(A89279)

$fgAlpha     = FBD5AE
$purpleAlpha = 694E68
