[colors-dark]
foreground=839395
background=001a1f
selection-background=003842

## Normal/regular colors (color palette 0-7)
regular0=07404a  # black
regular1=de322e  # red
regular2=869900  # green
regular3=b28700  # yellow
regular4=278bd2  # blue
regular5=d53683  # magenta
regular6=2a9f97  # cyan
regular7=e8e4cf  # white

## Bright colors (color palette 8-15)
bright0=587175   # bright black
bright1=f56762   # bright red
bright2=a9c81c   # bright green
bright3=dcb028   # bright yellow
bright4=5ba2df   # bright blue
bright5=e167a5   # bright magenta
bright6=55b5ad   # bright cyan
bright7=fdf6e3   # bright white

## Dimmed colors
dim0=c94c16      # orange (Osaka standard orange)
dim1=003842      # bg_red (selection background)
