# Rxyhn Earthy Pine for Kitty
background #012423
foreground #FBD5AE
cursor     #FBD5AE
selection_background #324440
selection_foreground #FBD5AE

color0  #1C3A38
color8  #324440
color1  #D4493F
color9  #D4493F
color2  #90B640
color10 #90B640
color3  #E5B73E
color11 #E5B73E
color4  #3C7B80
color12 #3C7B80
color5  #694E68
color13 #694E68
color6  #5EA89A
color14 #5EA89A
color7  #FBD5AE
color15 #E9C8A1
